export interface Products {
    url?: string,
    id?: number,
    fk_user_product?: number
    type?: string,
    category?: string,    
    name?: string,
    description?: string,
    price?: number,    
    rate?: number,
    amount?: number,
    orders?: number,
    subImage1?: string,
    subImage2?: string,
    subImage3?: string,
    color?: string,
    size?: string,
    mark?: string,    
    featured?: boolean,
    newest?: boolean,
}
